# Generated by Django 5.1.2 on 2024-10-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, upload_to="menu/"),
        ),
    ]
