# Generated by Django 5.1.2 on 2024-10-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0003_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ordered_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
