# Generated by Django 5.1.2 on 2024-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0004_user_ordered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
