# Generated by Django 5.1.2 on 2024-10-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersApp", "0005_address_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="home", max_length=100),
            preserve_default=False,
        ),
    ]
