# Generated by Django 5.1.2 on 2024-10-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, upload_to="menu/"),
        ),
    ]
