# Generated by Django 5.1.2 on 2024-10-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_menuitem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
