# Generated by Django 5.1.2 on 2024-11-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_menurecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="rating",
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
