# Generated by Django 5.1.2 on 2024-11-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_menuitem_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_buy_one",
            field=models.BooleanField(default=False),
        ),
    ]
