# Generated by Django 5.1.2 on 2024-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="uuid",
            field=models.CharField(
                default="sad", editable=False, max_length=10, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("Ondelivery", "Ondelivery"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
