# Generated by Django 5.1.2 on 2024-10-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_adminnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, upload_to="orders/"),
        ),
    ]
