# Generated by Django 5.1.2 on 2024-10-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_order",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
