# Generated by Django 5.1.2 on 2024-10-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderrecommendation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderRecommendation",
        ),
    ]
