# Generated by Django 5.1.2 on 2024-10-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_alter_order_user_usercart"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
