# Generated by Django 5.1.2 on 2024-10-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_notificationuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationuser",
            name="description",
        ),
    ]
