# Generated by Django 5.1.2 on 2024-11-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_adminnotification_stamp_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rating",
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
