# Generated by Django 5.1.2 on 2024-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_alter_order_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="rating",
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
