# Generated by Django 5.1.2 on 2024-12-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_alter_order_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_attended",
            field=models.BooleanField(default=False),
        ),
    ]
