# Generated by Django 5.1.2 on 2024-12-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_order_is_attended"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("status", models.CharField(max_length=100)),
                ("stamp_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="usercart",
            name="verification_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
