# Generated by Django 5.1.2 on 2024-12-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_order_is_attended"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_reference_number",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="success",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
